apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: kubectl-test
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/k8s/kubectl-test/releases/download/v0.1.0/kubectl-test_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./kubectl-test"
      to: "."
    - from: LICENSE
      to: "."
    bin: "kubectl-test"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/k8s/kubectl-test/releases/download/v0.1.0/kubectl-test_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./kubectl-test"
      to: "."
    - from: LICENSE
      to: "."
    bin: "kubectl-test"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/k8s/kubectl-test/releases/download/v0.1.0/kubectl-test_windows_amd64.zip
    sha256: ""
    files:
    - from: "/kubectl-test.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "kubectl-test.exe"
  shortDescription: A new plugin
  homepage: https://github.com/k8s/kubectl-test
  caveats: |
    Usage:
      $ kubectl kubectl-test

    For additional options:
      $ kubectl kubectl-test --help
      or https://github.com/k8s/kubectl-test/blob/v0.1.0/doc/USAGE.md

  description: |
    This is a new plugin
